// Mocks generated by Mockito 5.4.6 from annotations
// in nexus_app/test/mocks/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i14;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nexus_app/core/errors/failures.dart' as _i7;
import 'package:nexus_app/core/platform/haptic_channel.dart' as _i15;
import 'package:nexus_app/core/theme/app_theme.dart' as _i13;
import 'package:nexus_app/core/theme/theme_provider.dart' as _i12;
import 'package:nexus_app/features/conversation/domain/entities/message_entity.dart'
    as _i8;
import 'package:nexus_app/features/conversation/domain/repositories/conversation_repository.dart'
    as _i5;
import 'package:nexus_app/features/monetization/domain/entities/product_entity.dart'
    as _i11;
import 'package:nexus_app/features/monetization/domain/repositories/monetization_repository.dart'
    as _i10;
import 'package:nexus_app/features/persona/domain/entities/persona_entity.dart'
    as _i3;
import 'package:nexus_app/features/persona/domain/repositories/persona_repository.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonaEntity_1 extends _i1.SmartFake implements _i3.PersonaEntity {
  _FakePersonaEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_2 extends _i1.SmartFake implements _i4.ThemeData {
  _FakeThemeData_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [ConversationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRepository extends _i1.Mock
    implements _i5.ConversationRepository {
  MockConversationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.LlmFailure, _i8.MessageEntity>> sendMessage({
    required String? userId,
    required String? content,
    required _i3.PersonaEntity? persona,
    required List<_i8.MessageEntity>? history,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #userId: userId,
            #content: content,
            #persona: persona,
            #history: history,
          },
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.LlmFailure, _i8.MessageEntity>>.value(
                _FakeEither_0<_i7.LlmFailure, _i8.MessageEntity>(
          this,
          Invocation.method(
            #sendMessage,
            [],
            {
              #userId: userId,
              #content: content,
              #persona: persona,
              #history: history,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.LlmFailure, _i8.MessageEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.VectorDbFailure, String>> loadRagContext({
    required String? userId,
    required String? queryText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadRagContext,
          [],
          {
            #userId: userId,
            #queryText: queryText,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.VectorDbFailure, String>>.value(
            _FakeEither_0<_i7.VectorDbFailure, String>(
          this,
          Invocation.method(
            #loadRagContext,
            [],
            {
              #userId: userId,
              #queryText: queryText,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.VectorDbFailure, String>>);

  @override
  _i6.Future<_i2.Either<_i7.VectorDbFailure, void>> storeInteraction({
    required String? userId,
    required String? userInput,
    required String? aiResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeInteraction,
          [],
          {
            #userId: userId,
            #userInput: userInput,
            #aiResponse: aiResponse,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.VectorDbFailure, void>>.value(
            _FakeEither_0<_i7.VectorDbFailure, void>(
          this,
          Invocation.method(
            #storeInteraction,
            [],
            {
              #userId: userId,
              #userInput: userInput,
              #aiResponse: aiResponse,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.VectorDbFailure, void>>);
}

/// A class which mocks [PersonaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonaRepository extends _i1.Mock implements _i9.PersonaRepository {
  MockPersonaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PersonaEntity getMirrorPersona() => (super.noSuchMethod(
        Invocation.method(
          #getMirrorPersona,
          [],
        ),
        returnValue: _FakePersonaEntity_1(
          this,
          Invocation.method(
            #getMirrorPersona,
            [],
          ),
        ),
      ) as _i3.PersonaEntity);

  @override
  _i3.PersonaEntity getShadowPersona() => (super.noSuchMethod(
        Invocation.method(
          #getShadowPersona,
          [],
        ),
        returnValue: _FakePersonaEntity_1(
          this,
          Invocation.method(
            #getShadowPersona,
            [],
          ),
        ),
      ) as _i3.PersonaEntity);

  @override
  _i3.PersonaEntity getPrimePersona() => (super.noSuchMethod(
        Invocation.method(
          #getPrimePersona,
          [],
        ),
        returnValue: _FakePersonaEntity_1(
          this,
          Invocation.method(
            #getPrimePersona,
            [],
          ),
        ),
      ) as _i3.PersonaEntity);

  @override
  _i3.PersonaEntity? getUnlockedPersona(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getUnlockedPersona,
        [id],
      )) as _i3.PersonaEntity?);

  @override
  List<_i3.PersonaEntity> getAllPersonas(
          {List<String>? unlockedIds = const []}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPersonas,
          [],
          {#unlockedIds: unlockedIds},
        ),
        returnValue: <_i3.PersonaEntity>[],
      ) as List<_i3.PersonaEntity>);
}

/// A class which mocks [MonetizationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMonetizationRepository extends _i1.Mock
    implements _i10.MonetizationRepository {
  MockMonetizationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i11.ProductEntity>> getOfferings() => (super.noSuchMethod(
        Invocation.method(
          #getOfferings,
          [],
        ),
        returnValue:
            _i6.Future<List<_i11.ProductEntity>>.value(<_i11.ProductEntity>[]),
      ) as _i6.Future<List<_i11.ProductEntity>>);

  @override
  _i6.Future<void> purchaseProduct(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #purchaseProduct,
          [productId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> restorePurchases() => (super.noSuchMethod(
        Invocation.method(
          #restorePurchases,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> hasArenaAccess() => (super.noSuchMethod(
        Invocation.method(
          #hasArenaAccess,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> hasLegacyAccess() => (super.noSuchMethod(
        Invocation.method(
          #hasLegacyAccess,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<Set<String>> getActiveEntitlements() => (super.noSuchMethod(
        Invocation.method(
          #getActiveEntitlements,
          [],
        ),
        returnValue: _i6.Future<Set<String>>.value(<String>{}),
      ) as _i6.Future<Set<String>>);
}

/// A class which mocks [NexusThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNexusThemeProvider extends _i1.Mock
    implements _i12.NexusThemeProvider {
  MockNexusThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.NexusThemeType get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i13.NexusThemeType.mirror,
      ) as _i13.NexusThemeType);

  @override
  _i4.ThemeData get currentTheme => (super.noSuchMethod(
        Invocation.getter(#currentTheme),
        returnValue: _FakeThemeData_2(
          this,
          Invocation.getter(#currentTheme),
        ),
      ) as _i4.ThemeData);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setTheme(_i13.NexusThemeType? next) => super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [next],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void triggerFracture() => super.noSuchMethod(
        Invocation.method(
          #triggerFracture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void activateArena() => super.noSuchMethod(
        Invocation.method(
          #activateArena,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetToMirror() => super.noSuchMethod(
        Invocation.method(
          #resetToMirror,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NexusHapticChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockNexusHapticChannel extends _i1.Mock
    implements _i15.NexusHapticChannel {
  MockNexusHapticChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> triggerFractureHaptic() => (super.noSuchMethod(
        Invocation.method(
          #triggerFractureHaptic,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> triggerArenaHaptic() => (super.noSuchMethod(
        Invocation.method(
          #triggerArenaHaptic,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
